<h3>
    Les produits
    <a href="admin?task=validateProducts"><i class="fas fa-chevron-left"></i></a>
    <a href="admin?task=newProducts"><i class="fas fa-plus"></i></a>
</h3>
<p class="indication">Ajoutez un nouveau produit avec le bouton +.<br>
                      Scrollez de gauche à droite pour découvrir toutes les données du produit.<br>
                      Scrollez de haut en bas pour découvrir tous les produits.<br>
                      Modifiez le ou les éléments d'un produit puis validez la ligne, ou supprimez-le.
</p>
<div>
    <p id="message" class="errorMessage"></p>
</div>
<?php if (hasFlashes('error')): ?>
    <div>
        <?php foreach (getFlashes('error') as $message): ?>
            <p class="errorMessage"><?= $message ?></p>
        <?php endforeach?>
    </div>
<?php endif?>
<div class="tableLong">
    <table>
        <thead>
            <tr>
                <th>Catégories</th>
                <th>Produits</th>
                <th>Photos</th>
                <th>Descriptions</th>
                <th>Allergènes</th>
                <th>Status</th>
                <th>Quantités</th>
                <th>Prix</th> 
                <th></th>
                <th></th> 
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product): ?>  
                <tr>
                    <form action="updateProduct?id=<?=intval($product['Id'])?>" method="post"  enctype="multipart/form-data" id="updateProduct">
                        <td>
                            <div>
                                <label for="categoryProduct<?=intval($product['Id'])?>"></label>
                                <select name="categoryUpdateProduct" id="categoryProduct<?=intval($product['Id'])?>">
                                    <?php foreach ($categories as $categorie) : ?>
                                        <option
                                            value="<?=intval($categorie['Id'])?>"
                                            <?php if ($categorie['Id'] === $product['CategoryId']):?>
                                                <?= 'selected'; ?>
                                            <?php endif; ?>
                                        >
                                            <?=$categorie['Name']?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="nameProduct<?=intval($product['Id'])?>"></label>
                                <input type="text" id="nameProduct<?=intval($product['Id'])?>" name="nameUpdateProduct" value="<?=htmlspecialchars($product['Name'])?>" onblur="updateProductValue(<?=htmlspecialchars($product['Name'])?>,this.name,this.id)" required/>
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="imageProduct<?=intval($product['Id'])?>"></label>
                                <input type="file" id="imageProduct<?=intval($product['Id'])?>" name="imageUpdateProduct" value="<?=intval($product['Photo'])?>" accept="image/png, image/jpeg" onblur="updateProductValue(this.value,this.name,this.id)"/>
                                <input type="hidden" name="photoProduct" value="<?=$product['Photo']?>"/>
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="descriptionProduct<?=intval($product['Id'])?>"></label>
                                <textarea id="descriptionProduct<?=intval($product['Id'])?>" name="descriptionUpdateProduct" maxlength="100" onblur="updateProductValue(this.value,this.name,this.id)" required><?=htmlspecialchars($product['Description'])?></textarea>
                            </div>
                        </td>
                        <td>
                            <div class="allergens">
                                <?php foreach ($allergens as $allergen) : ?>
                                    <div>
                                        <input type="checkbox" id="checkboxLabel<?=intval($allergen['Id'])?>" name="allergensUpdate<?=intval($allergen['Id'])?>" value="<?=intval($allergen['Id'])?>" 
                                            <?php $findAllAllergensByIdProducts = findAllAllergensByIdProduct($pdo, $product['Id']);
                                            foreach ($findAllAllergensByIdProducts as $findAllAllergensByIdProduct): ?>
                                                <?php if ($allergen['Id'] === $findAllAllergensByIdProduct['Id']) :?>
                                                    <?= 'checked'; ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        />
                                        <label class="checkboxLabel" for="checkboxLabel<?=intval($allergen['Id'])?>"><?=htmlspecialchars($allergen['Name'])?></label>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="statusProduct<?=intval($product['Id'])?>"></label>
                                <select name="statusUpdateProduct" id="statusProduct<?=intval($product['Id'])?>">
                                    <option
                                        value="Loading"
                                        <?php if ($product['Status'] === 'Loading'):?>
                                            <?= 'selected'; ?>
                                        <?php endif; ?>
                                    >
                                        En attente
                                    </option>  
                                    <option 
                                        value="Card"
                                        <?php if ($product['Status'] === 'Card') :?>
                                            <?= 'selected'; ?>
                                        <?php endif; ?>
                                    >
                                        A la carte
                                    </option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="quantityProduct"<?=intval($product['Id'])?>></label>
                                <input type="number" id="quantityProduct<?=intval($product['Id'])?>" name="quantityUpdateProduct" value="<?=intval($product['QuantityInStock'])?>" onblur="updateProductValue(this.value,this.name,this.id)"/>
                            </div>
                        </td>
                        <td>
                            <div>
                                <label for="priceProduct<?=intval($product['Id'])?>"></label>
                                <input type="number"  min="0" step="0.01" id="priceProduct<?=intval($product['Id'])?>" name="priceUpdateProduct" value="<?=number_format(floatval($product['Price']), 2, '.', ' ')?>" onblur="updateProductValue(this.value,this.name,this.id)"/>
                            </div>
                        </td>
                        <td>
                            <button type="submit"><i class="fas fa-check" onclick="return validateUpdateProduct()"></i></button>
                        </td>
                    </form>
                    <form action="deleteProduct?id=<?=intval($product['Id'])?>" method="post"> 
                        <td>
                            <button class="check" type="submit" onclick="return confirm('Êtes vous sur de vouloir supprimer ?')"><i class="fas fa-times"></i></button>
                        </td>
                    </form>
                </tr>
            <?php endforeach; ?>    
        </tbody>
    </table>
</div>