<!-- HomePage -->
<div class="modal cart">
    <h2>Bienvenue sur notre restaurant numérique</h2>
    <p>Faites vous servir nos succulents hamburgers fait maison, après quelques clics.</p>
    <p>Laissez-vous guider, pas à pas. </p>
    <p>Tout d'abord, vous devez vous inscrire avec seulement votre email et un mot de passe. <br>
        On ne vous en demande pas plus!<br>
        Pour les habitués, vous pouvez directement vous connecter! </p>
    <div class="btn">
        <a href="account" class="button">Inscription</a>
        <a href="login" class="button">Connexion</a>
    </div>
</div>
<!-- End HomePage -->