<!-- ConnexionPage -->
<div class="modal cart" id="ConnexionPage">
    <h2>Connexion</h2>
    <form action="login" method="post" id="login">
        <div>
            <label for="userMail"> Entrez votre e-mail :</label>
            <input type="email" id="userMail" name="userMail" value="leburger@gmail.fr" onClick="eraseValue('leburger@gmail.fr',this.id)" onMouseOut="restoreValue('leburger@gmail.fr',this.id)" onblur="verifyValue(this.id)" required>
        </div>
        <div>
            <label for="userPassword"> Entrez votre mot de passe (8 caractères minimum) :</label>
            <input type="password" id="userPassword" name="userPassword" minlength="8" value="Mot de passe" onClick="eraseValue('Mot de passe',this.id)" onMouseOut="restoreValue('Mot de passe',this.id)" onblur="verifyValue(this.id)" required>
        </div>
        <div>
            <p id="message" class="errorMessage"></p>
        </div>
        <?php if (hasFlashes('error')): ?>
            <div>
                <?php foreach (getFlashes('error') as $message): ?>
                    <p class="errorMessage"><?= $message ?></p>
                <?php endforeach?>
            </div>
        <?php endif?>
        <div class="btn">
            <button type="submit" class="button" onclick="return validateLogin()">Connexion</button>
        </div>
    </form>
</div>
<!-- End ConnexionPage -->